export const mockCompetitionTeamResult = {
  count: 45,
  filters: {},
  competition: {
    id: 2001,
    area: {
      id: 2077,
      name: 'Europe',
    },
    name: 'UEFA Champions League',
    code: 'CL',
    plan: 'TIER_ONE',
    lastUpdated: '2021-06-26T13:37:26Z',
  },
  season: {
    id: 734,
    startDate: '2021-06-26',
    endDate: '2022-05-22',
    currentMatchday: 2,
    winner: null,
  },
  teams: [
    {
      id: 610,
      area: {
        id: 2247,
        name: 'Turkey',
      },
      name: 'Galatasaray SK',
      shortName: 'Galatasaray',
      tla: 'GAL',
      crestUrl: 'https://crests.football-data.org/610.svg',
      address:
        'Türk Telekom Arena Stadyumu, Huzur Mahallesi, Şişli İstanbul 34415',
      phone: '+90 (212) 3051905',
      website: 'http://www.galatasaray.org',
      email: 'info@galatasaray.org',
      founded: 1905,
      clubColors: 'Red / Yellow',
      venue: 'Türk Telekom Arena',
      lastUpdated: '2020-11-19T02:14:16Z',
    },
    {
      id: 654,
      area: {
        id: 2093,
        name: 'Greece',
      },
      name: 'PAE Olympiakos SFP',
      shortName: 'Olympiakos',
      tla: 'OLY',
      crestUrl: 'https://crests.football-data.org/654.svg',
      address: 'Plateia Alexandras Piraeus 18534',
      phone: '+30 (210) 4143000',
      website: 'http://www.olympiacos.org',
      email: 'info@olympiacos.org',
      founded: 1925,
      clubColors: 'Red / White',
      venue: 'Stadio Georgios Karaiskáki',
      lastUpdated: '2020-11-26T02:21:34Z',
    },
    {
      id: 674,
      area: {
        id: 2163,
        name: 'Netherlands',
      },
      name: 'PSV',
      shortName: 'PSV',
      tla: 'PSV',
      crestUrl: 'https://crests.football-data.org/674.svg',
      address: 'Fredriklaan 10a Eindhoven 5616 NH',
      phone: '+31 (040) 2505501',
      website: 'http://www.psv.nl',
      email: 'info@psv.nl',
      founded: 1913,
      clubColors: 'Red / White',
      venue: 'Philips Stadion',
      lastUpdated: '2020-11-19T02:07:14Z',
    },
    {
      id: 732,
      area: {
        id: 2204,
        name: 'Scotland',
      },
      name: 'Celtic FC',
      shortName: 'Celtic',
      tla: 'CEL',
      crestUrl: 'https://crests.football-data.org/732.svg',
      address: 'Celtic Park Glasgow G40 3RE',
      phone: '+44 (871) 2261888',
      website: 'http://www.celticfc.co.uk',
      email: 'comments@celticfc.com',
      founded: 1887,
      clubColors: 'Green / White',
      venue: 'Celtic Park',
      lastUpdated: '2021-02-06T18:16:56Z',
    },
    {
      id: 749,
      area: {
        id: 2233,
        name: 'Sweden',
      },
      name: 'Malmö FF',
      shortName: 'Malmö FF',
      tla: 'MAL',
      crestUrl: 'https://crests.football-data.org/749.svg',
      address: 'Box 19067 Malmö 20073',
      phone: '+46 (040) 326600',
      website: 'http://www.mff.se',
      email: 'info@mff.se',
      founded: 1910,
      clubColors: 'Light Blue / White',
      venue: 'Eleda Stadion',
      lastUpdated: '2020-11-26T01:57:45Z',
    },
    {
      id: 755,
      area: {
        id: 2058,
        name: 'Croatia',
      },
      name: 'GNK Dinamo Zagreb',
      shortName: 'Dinamo Zagreb',
      tla: 'DIN',
      crestUrl: 'https://crests.football-data.org/755.svg',
      address: 'Maksimirska 128 Zagreb 10000',
      phone: '+385 (01) 2386111',
      website: 'http://gnkdinamo.hr',
      email: 'dinamo@gnkdinamo.hr',
      founded: 1903,
      clubColors: 'Blue / White',
      venue: 'Stadion Maksimir',
      lastUpdated: '2021-04-08T22:27:57Z',
    },
    {
      id: 884,
      area: {
        id: 2113,
        name: 'Israel',
      },
      name: 'Maccabi Haifa FC',
      shortName: 'Maccabi Haifa',
      tla: 'MHA',
      crestUrl: '',
      address: 'Heinrich Heine Str. 14 Haifa 33264',
      phone: '+972 (4) 8346626',
      website: 'http://mhaifafc.com',
      email: 'info@mhaifafc.com',
      founded: 1913,
      clubColors: 'Green / White',
      venue: 'Sammy Ofer Stadium',
      lastUpdated: '2020-11-26T02:17:06Z',
    },
    {
      id: 907,
      area: {
        id: 2062,
        name: 'Czech Republic',
      },
      name: 'AC Sparta Praha',
      shortName: 'Sparta Praha',
      tla: 'SPP',
      crestUrl: '',
      address: 'Milady Horakove 1066/98 Praha 17082',
      phone: '+420 (296) 111111',
      website: 'http://www.sparta.cz',
      email: 'football@sparta.cz',
      founded: 1893,
      clubColors: 'Blue / Yellow / Red',
      venue: 'Generali Arena',
      lastUpdated: '2020-11-26T02:11:47Z',
    },
    {
      id: 1105,
      area: {
        id: 2186,
        name: 'Poland',
      },
      name: 'Legia Warszawa',
      shortName: 'Legia',
      tla: 'LEG',
      crestUrl:
        'https://upload.wikimedia.org/wikipedia/commons/b/b5/Legia_Warszawa.svg',
      address: 'ul. Łazienkowska 3 Warszawa 00-449',
      phone: null,
      website: 'https://legiakosz.com',
      email: 'info@legiakosz.com',
      founded: 1929,
      clubColors: 'Red / White / Green',
      venue: 'Stadion Miejski Legii Warszawa im. Marszałka Józefa Piłsudskiego',
      lastUpdated: '2020-11-26T02:20:25Z',
    },
    {
      id: 1870,
      area: {
        id: 2012,
        name: 'Armenia',
      },
      name: 'FC Alashkert',
      shortName: 'Alashkert',
      tla: 'ALA',
      crestUrl: null,
      address: '25 Saryan Street Yerevan null',
      phone: '+374 (10) 520303',
      website: 'http://www.fcalashkert.am',
      email: 'info@fcalashkert.am',
      founded: 1990,
      clubColors: 'Black / Yellow',
      venue: 'Nairi',
      lastUpdated: '2020-09-10T02:45:31Z',
    },
    {
      id: 1871,
      area: {
        id: 2234,
        name: 'Switzerland',
      },
      name: 'BSC Young Boys',
      shortName: 'Young Boys',
      tla: 'YOB',
      crestUrl: 'https://crests.football-data.org/1871.svg',
      address: 'Postfach 61 Bern 3000',
      phone: '+41 (31) 3448000',
      website: 'http://www.bscyb.ch',
      email: 'info@bscyb.ch',
      founded: 1898,
      clubColors: 'Yellow / Black',
      venue: 'Wankdorfstadion',
      lastUpdated: '2020-11-26T02:23:09Z',
    },
    {
      id: 1880,
      area: {
        id: 2151,
        name: 'Moldova',
      },
      name: 'FC Sheriff Tiraspol',
      shortName: 'Sheriff',
      tla: 'SHE',
      crestUrl: 'https://crests.football-data.org/1880.svg',
      address: 'ul. K. Libnekhta 1/2 Tiraspol 3300',
      phone: '+373 (533) 363500',
      website: 'http://www.fc-sheriff.com',
      email: 'club@sc.sheriff.md',
      founded: 1997,
      clubColors: 'Yellow / Black',
      venue: 'Bolshaya Sportivnaya Arena',
      lastUpdated: '2020-09-03T15:05:23Z',
    },
    {
      id: 1885,
      area: {
        id: 2154,
        name: 'Montenegro',
      },
      name: 'FK Budućnost Podgorica',
      shortName: 'Budućnost',
      tla: 'BUD',
      crestUrl: null,
      address: 'Vaka Djurovica bb Podgorica 81000',
      phone: '+382 (020) 667080',
      website: 'http://www.fkbuducnost.me',
      email: null,
      founded: 1925,
      clubColors: 'Blue / White',
      venue: 'Stadion Pod Goricom',
      lastUpdated: '2020-09-10T02:45:48Z',
    },
    {
      id: 1890,
      area: {
        id: 2135,
        name: 'Lithuania',
      },
      name: 'FK Žalgiris Vilnius',
      shortName: 'Žalgiris',
      tla: 'ZAL',
      crestUrl: null,
      address: 'Žolyno gatvė 29 Vilnius 2040',
      phone: '+370 (5) 23752791',
      website: 'http://www.fkzalgiris.lt',
      email: 'info@fkzalgiris.lt',
      founded: 1947,
      clubColors: 'Green / White',
      venue: 'Vilniaus LFF stadionas',
      lastUpdated: '2020-11-05T02:00:05Z',
    },
    {
      id: 1892,
      area: {
        id: 2143,
        name: 'Malta',
      },
      name: 'Hibernians FC',
      shortName: 'Hibernians',
      tla: 'HIB',
      crestUrl: null,
      address: '158, Antoine De Paule Square Paola null',
      phone: '+356 (9942) 0711',
      website: 'http://www.hiberniansfc.org',
      email: 'secretary@hiberniansfc.org',
      founded: 1922,
      clubColors: null,
      venue: 'MFA Centenary Stadium',
      lastUpdated: '2020-11-26T02:17:06Z',
    },
    {
      id: 1896,
      area: {
        id: 2171,
        name: 'Northern Ireland',
      },
      name: 'Linfield FC',
      shortName: 'Linfield',
      tla: 'LIN',
      crestUrl: 'https://crests.football-data.org/1896.svg',
      address: 'null Belfast null',
      phone: null,
      website: 'http://www.linfieldfc.com',
      email: 'webdirector@linfieldfc.com',
      founded: 1886,
      clubColors: 'Blue / White',
      venue: 'Windsor Park',
      lastUpdated: '2020-09-10T02:46:05Z',
    },
    {
      id: 1901,
      area: {
        id: 2035,
        name: 'Bulgaria',
      },
      name: 'PFK Ludogorets 1945 Razgrad',
      shortName: 'Ludogorets',
      tla: 'LUD',
      crestUrl: 'https://crests.football-data.org/1901.svg',
      address: 'null Razgrad 7200',
      phone: '+359 (899) 141129',
      website: 'http://www.ludogorets.com',
      email: 'office@ludogorets.com',
      founded: 2000,
      clubColors: 'Green / White',
      venue: 'Huvepharma Arena',
      lastUpdated: '2020-11-26T02:19:58Z',
    },
    {
      id: 2014,
      area: {
        id: 2016,
        name: 'Austria',
      },
      name: 'SK Rapid Wien',
      shortName: 'Rapid Wien',
      tla: 'RAP',
      crestUrl: 'https://crests.football-data.org/2014.svg',
      address: 'Keisslergasse 3 Wien 1140',
      phone: '+43 (1) 727430',
      website: 'http://www.skrapid.at',
      email: 'info@skrapid.com',
      founded: 1898,
      clubColors: 'Green / White',
      venue: 'Allianz Stadion',
      lastUpdated: '2021-05-22T07:47:10Z',
    },
    {
      id: 2921,
      area: {
        id: 2192,
        name: 'Republic of Ireland',
      },
      name: 'Shamrock Rovers FC',
      shortName: 'Shamrock Rov',
      tla: 'SHR',
      crestUrl: null,
      address: 'Whitestown Way  Tallaght Dublin 24',
      phone: '+353 (1) 4605948',
      website: 'http://www.shamrockrovers.ie',
      email: 'shamrockrovers@clubi.ie',
      founded: 1901,
      clubColors: 'Green / White',
      venue: 'Tallaght Stadium',
      lastUpdated: '2020-10-22T01:56:36Z',
    },
    {
      id: 4271,
      area: {
        id: 2030,
        name: 'Bosnia and Herzegovina',
      },
      name: 'FK Borac Banja Luka',
      shortName: 'Borac BL',
      tla: 'BOR',
      crestUrl: null,
      address: 'Vladike Platona 6 Banja Luka 78000',
      phone: '+387 (51) 312455',
      website: 'http://www.fkborac.net',
      email: 'kontakt@fkborac.net',
      founded: 1926,
      clubColors: 'Red / Blue',
      venue: 'Gradski Stadion',
      lastUpdated: '2020-11-26T02:03:39Z',
    },
    {
      id: 4485,
      area: {
        id: 2065,
        name: 'Denmark',
      },
      name: 'FC Midtjylland',
      shortName: 'Midtjylland',
      tla: 'MID',
      crestUrl: 'https://crests.football-data.org/4485.svg',
      address: 'Kaj Zartows Vej 5, Postboks 287 Herning 7400',
      phone: '+45 (96) 271040',
      website: 'http://www.fcm.dk',
      email: 'fcmidtjylland@fc-mj.dk',
      founded: 1999,
      clubColors: 'Black / Red',
      venue: 'MCH Arena',
      lastUpdated: '2020-11-26T02:15:06Z',
    },
    {
      id: 5100,
      area: {
        id: 2075,
        name: 'Estonia',
      },
      name: 'FC Flora',
      shortName: 'Flora',
      tla: 'FLO',
      crestUrl: null,
      address: 'Asula 4c Tallinn 11312',
      phone: '+372 (627) 9940',
      website: 'http://www.fcflora.ee',
      email: 'fcflora@fcflora.ee',
      founded: 1990,
      clubColors: 'Green / White',
      venue: 'A. Le Coq Arena',
      lastUpdated: '2020-11-05T01:59:34Z',
    },
    {
      id: 5123,
      area: {
        id: 2080,
        name: 'Finland',
      },
      name: 'Helsingin JK',
      shortName: 'HJK',
      tla: null,
      crestUrl: 'https://crests.football-data.org/5123.svg',
      address: 'Urheilukatu 5 Helsinki 00250',
      phone: '+358 (9) 74216600',
      website: 'http://www.hjk.fi',
      email: 'hjk@hjk.fi',
      founded: 1907,
      clubColors: 'Blue / White',
      venue: 'Telia 5G -areena',
      lastUpdated: '2021-05-09T09:33:44Z',
    },
    {
      id: 5142,
      area: {
        id: 2264,
        name: 'Wales',
      },
      name: "Connah's Quay Nomads FC",
      shortName: "Connah's Quay",
      tla: 'COQ',
      crestUrl: null,
      address: "Deeside Stadium, Kelserton Road Connah's Quay CH5 4BR",
      phone: '+44 (1244) 816418',
      website: 'http://www.the-nomads.co.uk',
      email: 'trevor.green@the-nomads.co.uk',
      founded: 1946,
      clubColors: 'Red / White',
      venue: 'Deeside College Stadium',
      lastUpdated: '2020-11-26T02:21:05Z',
    },
    {
      id: 5515,
      area: {
        id: 2194,
        name: 'Romania',
      },
      name: 'FC CFR 1907 Cluj',
      shortName: 'CFR Cluj',
      tla: 'CLU',
      crestUrl: 'https://crests.football-data.org/5515.svg',
      address: 'Str. Romulus Vuia, nr. 23 Cluj-Napoca 400214',
      phone: '+40 (264) 598831',
      website: 'http://www.cfr1907.ro',
      email: 'club@cfr-ecomax.ro',
      founded: 1907,
      clubColors: 'Claret / White',
      venue: 'Stadionul Dr. Constantin Rădulescu',
      lastUpdated: '2021-06-30T09:11:03Z',
    },
    {
      id: 5721,
      area: {
        id: 2173,
        name: 'Norway',
      },
      name: 'FK Bodø/Glimt',
      shortName: 'Bodø/Glimt',
      tla: null,
      crestUrl: null,
      address: 'Postboks 179 Bodø 8001',
      phone: '+47 (75) 545500',
      website: 'http://www.glimt.no',
      email: 'bg@glimt.no',
      founded: 1916,
      clubColors: 'Yellow / Black',
      venue: 'Aspmyra Stadion',
      lastUpdated: '2021-05-18T11:24:16Z',
    },
    {
      id: 5826,
      area: {
        id: 2129,
        name: 'Latvia',
      },
      name: 'Rīga FC',
      shortName: 'Rīga FC',
      tla: 'RFC',
      crestUrl: 'https://crests.football-data.org/5826.svg',
      address: 'Balasta Dambis 70b-1 Rīga null',
      phone: '+371 28861168',
      website: 'http://www.rigafc.lv',
      email: 'info@rigafc.lv',
      founded: 2014,
      clubColors: 'Blue / White',
      venue: 'Stadions Skonto',
      lastUpdated: '2020-11-12T01:59:46Z',
    },
    {
      id: 5945,
      area: {
        id: 2107,
        name: 'Iceland',
      },
      name: 'KF Valur',
      shortName: 'Valur',
      tla: 'VAL',
      crestUrl: null,
      address: 'Laufásvegi, Hlíðarendi Reykjavík 101',
      phone: '+354 (414) 8005',
      website: 'http://www.valur.is',
      email: 'valur@valur.is',
      founded: 1911,
      clubColors: 'Red / White',
      venue: 'Origo Völlurinn',
      lastUpdated: '2020-09-10T02:16:14Z',
    },
    {
      id: 5954,
      area: {
        id: 2106,
        name: 'Hungary',
      },
      name: 'Ferencvárosi TC',
      shortName: 'Ferencváros',
      tla: 'FTC',
      crestUrl: 'https://crests.football-data.org/5954.svg',
      address: 'Üllöi út 129. Budapest 1091',
      phone: '+36 (1) 2156023',
      website: 'http://www.fradi.hu',
      email: 'ftcrt@ftc.hu',
      founded: 1899,
      clubColors: 'Green / White',
      venue: 'Groupama Arena',
      lastUpdated: '2021-02-06T18:12:19Z',
    },
    {
      id: 7281,
      area: {
        id: 2090,
        name: 'Gibraltar',
      },
      name: 'Lincoln Red Imps FC',
      shortName: 'Lincoln',
      tla: 'LIN',
      crestUrl: null,
      address: '64 Red Sands House, PO Box 1411 Gibraltar null',
      phone: '+350 54005985',
      website: 'http://www.lincolnredimpsfc.com',
      email: 'lincolnredimps@hotmail.com',
      founded: 1976,
      clubColors: 'White / Red',
      venue: 'Victoria Stadium',
      lastUpdated: '2020-09-10T02:49:06Z',
    },
    {
      id: 7283,
      area: {
        id: 2206,
        name: 'Serbia',
      },
      name: 'FK Crvena Zvezda',
      shortName: 'Crvena Zvedza',
      tla: 'CRV',
      crestUrl: 'https://crests.football-data.org/7283.svg',
      address: 'Ljutice Bogdana 1a Beograd 11000',
      phone: '+381 (11) 3672060',
      website: 'http://www.crvenazvezdafk.com',
      email: 'office@crvenazvezdafk.com',
      founded: 1945,
      clubColors: 'Red / White',
      venue: 'Stadion Rajko Mitić',
      lastUpdated: '2020-09-03T15:05:25Z',
    },
    {
      id: 7285,
      area: {
        id: 2083,
        name: 'FYR Macedonia',
      },
      name: 'KF Shkëndija 79',
      shortName: 'Shkëndija 79',
      tla: 'SHK',
      crestUrl: null,
      address: 'ul. Blagoya Toska Tetovo 1200',
      phone: '+389 (443) 53670',
      website: 'http://www.kfshkendija.com/',
      email: 'kfshkendija@yahoo.com',
      founded: 1979,
      clubColors: 'Black / Red',
      venue: 'Ecolog Arena',
      lastUpdated: '2020-09-10T02:49:15Z',
    },
    {
      id: 7474,
      area: {
        id: 2124,
        name: 'Kosovo',
      },
      name: 'FC Prishtina',
      shortName: 'FC Prishtina',
      tla: 'FCP',
      crestUrl: null,
      address: 'Stadiumi i qytetit Rr. Fehmi Agani Prishtinë null',
      phone: '+381 (038) 226968',
      website: 'http://www.prishtinafc.com',
      email: 'rejupi@prishtinafc.com',
      founded: 1922,
      clubColors: 'Blue / White',
      venue: 'Stadiumi Fadil Vokrri',
      lastUpdated: '2020-09-10T02:49:26Z',
    },
    {
      id: 7479,
      area: {
        id: 2200,
        name: 'San Marino',
      },
      name: 'SS Folgore/Falciano',
      shortName: 'SS Folgore',
      tla: 'FOL',
      crestUrl: null,
      address: 'Str La Zanetta, 10 Falciano 47891',
      phone: '+39 (335) 6950461',
      website: 'http://www.folgorecalcio.com',
      email: 'info@folgorecalcio.com',
      founded: 1972,
      clubColors: 'Red / Yellow / Black',
      venue: "Stadio Fonte Dell'Ovo",
      lastUpdated: '2019-05-23T02:25:38Z',
    },
    {
      id: 7480,
      area: {
        id: 2136,
        name: 'Luxembourg',
      },
      name: 'CS Fola Esch',
      shortName: 'Fola Esch',
      tla: 'FOL',
      crestUrl: null,
      address: 'B.P. 83 Esch-sur-Alzette 4001',
      phone: '+352 530995',
      website: 'http://www.csfola.lu',
      email: 'info@csfola.lu',
      founded: 1906,
      clubColors: 'Red / White',
      venue: 'Stade Émile Mayrisch',
      lastUpdated: '2020-09-03T03:18:30Z',
    },
    {
      id: 7482,
      area: {
        id: 2087,
        name: 'Georgia',
      },
      name: 'FC Dinamo Tbilisi',
      shortName: 'Dinamo Tbilisi',
      tla: 'DIN',
      crestUrl: null,
      address: 'Boris Paichadze Street 1 Tbilisi 0159',
      phone: '+995 (32) 2518877',
      website: 'http://www.fcdinamo.ge',
      email: 'info@fcdinamo.ge',
      founded: 1925,
      clubColors: 'Dark Blue / Light Blue / White',
      venue: 'Boris Paichadzis Dinamo Arena',
      lastUpdated: '2020-09-03T03:18:33Z',
    },
    {
      id: 7493,
      area: {
        id: 2017,
        name: 'Azerbaijan',
      },
      name: 'Neftçi PFK',
      shortName: 'Neftçi',
      tla: 'NEF',
      crestUrl: null,
      address: 'Nobel Prospekti No.64 Bakı null',
      phone: '+994 (012) 4244640',
      website: 'http://www.neftchipfk.com',
      email: 'office@neftchipfk.com',
      founded: 1937,
      clubColors: 'Black / White',
      venue: 'Bakcell Arena',
      lastUpdated: '2020-09-03T03:02:36Z',
    },
    {
      id: 7498,
      area: {
        id: 2022,
        name: 'Belarus',
      },
      name: 'FK Šachcior Salihorsk',
      shortName: 'Šachcior S.',
      tla: 'SOL',
      crestUrl: null,
      address: 'Lenin str.38 Salihorsk 223710',
      phone: '+375 (1710) 20621',
      website: 'http://www.fcshakhter.by',
      email: 'info@fcshakhter.by',
      founded: 1961,
      clubColors: 'Yellow / Black',
      venue: 'Stadyen Budaŭnik',
      lastUpdated: '2020-09-03T03:02:41Z',
    },
    {
      id: 7501,
      area: {
        id: 2119,
        name: 'Kazakhstan',
      },
      name: 'Qaırat Almaty FK',
      shortName: 'Qaırat Almaty',
      tla: 'QAI',
      crestUrl: null,
      address: 'null Almaty null',
      phone: null,
      website: 'http://www.fckairat.kz',
      email: 'info@fckairat.kz',
      founded: 1954,
      clubColors: 'Yellow / Blue',
      venue: 'Ortalıq Stadion',
      lastUpdated: '2020-09-03T03:02:44Z',
    },
    {
      id: 7509,
      area: {
        id: 2214,
        name: 'Slovakia',
      },
      name: 'ŠK Slovan Bratislava',
      shortName: 'Sl. Bratislava',
      tla: 'SBA',
      crestUrl: 'https://crests.football-data.org/7509.svg',
      address: 'Viktoria Tegelhoffa 4 Bratislava 83104',
      phone: '+421 (2) 44636363',
      website: 'http://www.skslovan.com',
      email: 'info@skslovan.com',
      founded: 1919,
      clubColors: 'Light Blue / White',
      venue: 'Štadión Tehelné pole',
      lastUpdated: '2020-09-03T15:05:25Z',
    },
    {
      id: 8166,
      area: {
        id: 2078,
        name: 'Faroe Islands',
      },
      name: 'HB',
      shortName: 'HB',
      tla: 'HB',
      crestUrl: null,
      address: 'Postsmoga 1333 Tórshavn 110',
      phone: '+298 314046',
      website: 'http://www.hb.fo',
      email: 'hb@hb.fo',
      founded: 1904,
      clubColors: 'Red / Black',
      venue: 'Gundadalur',
      lastUpdated: '2020-09-03T03:03:15Z',
    },
    {
      id: 8169,
      area: {
        id: 2215,
        name: 'Slovenia',
      },
      name: 'NŠ Mura',
      shortName: 'Mura',
      tla: 'MUR',
      crestUrl: null,
      address: 'Bade 45 S. 118 Murska Sobota 9000',
      phone: '+386 (02) 7872221',
      website: 'http://www.nsmura.si/',
      email: 'mura05@gmail.com',
      founded: 1924,
      clubColors: 'Black / White',
      venue: 'Mestni Štadion Fazanerija',
      lastUpdated: '2020-09-03T03:03:22Z',
    },
    {
      id: 8173,
      area: {
        id: 2002,
        name: 'Albania',
      },
      name: 'KF Teuta Durrës',
      shortName: 'Teuta Durrës',
      tla: 'TEU',
      crestUrl: null,
      address: 'Rruga A. Goga Durrës 2001',
      phone: '+355 (52) 221798',
      website: 'http://www.kfteuta.com',
      email: 'kfteuta@yahoo.com',
      founded: 1925,
      clubColors: 'Blue / White',
      venue: 'Stadiumi Niko Dovana',
      lastUpdated: '2020-09-03T03:03:25Z',
    },
    {
      id: 8912,
      area: {
        id: 2006,
        name: 'Andorra',
      },
      name: "Inter Club d'Escaldes",
      shortName: 'Inter Club',
      tla: 'INT',
      crestUrl: null,
      address: 'Plaça Coprínceps 1 Escaldes-Engordany AD570',
      phone: '+376 821753',
      website: 'https://www.interescaldes.com',
      email: 'interclubdescaldes@gmail.com',
      founded: 1991,
      clubColors: 'Blue / Black',
      venue: "Centre d'Entrenament de la FAF 1",
      lastUpdated: '2020-09-03T03:18:43Z',
    },
    {
      id: 8983,
      area: {
        id: 2061,
        name: 'Cyprus',
      },
      name: 'AS Omonia Lefkosía',
      shortName: 'Omonia',
      tla: 'OMO',
      crestUrl: null,
      address: 'Karpenioiou 19B Nicosia 1661',
      phone: '+357 (22) 875874',
      website: 'https://www.acomonia.com/',
      email: 'info@omonoia.com.cy',
      founded: 1948,
      clubColors: 'Green / White',
      venue: 'Neo GSP',
      lastUpdated: '2020-09-03T03:18:51Z',
    },
  ],
};

export const mockTeamProfileResult = {
  id: 610,
  area: { id: 2247, name: 'Turkey' },
  activeCompetitions: [
    {
      id: 2001,
      area: { id: 2077, name: 'Europe' },
      name: 'UEFA Champions League',
      code: 'CL',
      plan: 'TIER_ONE',
      lastUpdated: '2021-06-26T13:37:26Z',
    },
    {
      id: 2070,
      area: { id: 2247, name: 'Turkey' },
      name: 'Süper Lig',
      code: 'TSL',
      plan: 'TIER_THREE',
      lastUpdated: '2021-04-17T00:00:29Z',
    },
  ],
  name: 'Galatasaray SK',
  shortName: 'Galatasaray',
  tla: 'GAL',
  crestUrl: 'https://crests.football-data.org/610.svg',
  address: 'Türk Telekom Arena Stadyumu, Huzur Mahallesi, Şişli İstanbul 34415',
  phone: '+90 (212) 3051905',
  website: 'http://www.galatasaray.org',
  email: 'info@galatasaray.org',
  founded: 1905,
  clubColors: 'Red / Yellow',
  venue: 'Türk Telekom Arena',
  squad: [],
  lastUpdated: '2020-11-19T02:14:16Z',
};
